#!/usr/bin/expect
interp create -safe safeInterp
safeInterp invokehidden source /mnt/vars.config
lassign [safeInterp eval {list $user $pass}] user pass
spawn openconnect --user=$user --servercert pin-sha256:eFU51UIwCvUzkBR7o+FYSTK47aYHSR9XzJVphtGi4sw= https://hap.skat.dk
expect "Password" {send "$pass\r"}
interact